# Generated by Django 4.0.4 on 2022-05-29 23:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('approuve', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now=True)),
                ('dateDerniereModification', models.DateTimeField(auto_now_add=True)),
                ('uniteComptage', models.CharField(max_length=30)),
                ('masseUnite', models.FloatField()),
                ('image', models.FileField(upload_to='static/images/aliments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('tauxProteines', models.FloatField(default=0)),
                ('tauxLipides', models.FloatField(default=0)),
                ('tauxGlucides', models.FloatField(default=0)),
                ('mineraux', models.CharField(max_length=255, blank=True, null=True)),
                ('vitamines', models.CharField(max_length=255, blank=True, null=True)),
                ('detailApports', models.TextField(null=True)),
                ('detailRisques', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30)),
                ('motDePasse', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiblePourContributeur', models.BooleanField(default=True)),
                ('visiblePourProfessionnel', models.BooleanField(default=True)),
                ('dateDernierMessage', models.DateTimeField(null=True)),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributeur', to='app.contributeur')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionnel', to='app.contributeur')),
            ],
        ),
        migrations.CreateModel(
            name='OrigineRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('approuve', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now=True)),
                ('dateDerniereModification', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='static/images/repas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('momentJournee', models.IntegerField(choices=[(1, 'Matin'), (2, 'Midi'), (3, 'Soir')], null=True)),
                ('contributeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.originerepas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('detailRisques', models.TextField(null=True)),
                ('detailApports', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('approuve', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now=True)),
                ('dateDerniereModification', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='static/images/restaurants/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('adresse', models.CharField(max_length=100)),
                ('contributeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('repass', models.ManyToManyField(to='app.repas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepasConsomme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('momentJournee', models.IntegerField(choices=[(1, 'Matin'), (2, 'Midi'), (3, 'Soir')])),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repas')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aliment')),
                ('contributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contributeur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlimentRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aliment')),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='contributeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur'),
        ),
        migrations.AddField(
            model_name='aliment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typealiment'),
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('repas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.repas')),
                ('nombrePersonnes', models.IntegerField()),
                ('tempsPreparation', models.IntegerField(null=True)),
                ('tempsCuisson', models.IntegerField(null=True)),
                ('detailPreparation', models.TextField(null=True)),
                ('aliments', models.ManyToManyField(through='app.AlimentRecette', to='app.aliment')),
            ],
        ),
        migrations.AddField(
            model_name='alimentrecette',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recette'),
        ),
    ]
