# Generated by Django 4.0.4 on 2022-06-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributeur',
            name='professionnelSante',
            field=models.BooleanField(default=False, verbose_name='Professionnel de la santé'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='detailApports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='detailRisques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='motDePasse',
            field=models.CharField(max_length=255, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='nomUtilisateur',
            field=models.CharField(max_length=30, unique=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contributeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationsProfessionnels', to='app.contributeur'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='professionnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationsContributeurs', to='app.contributeur'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='detailPreparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repas',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repas',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='typealiment',
            name='detailApports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typealiment',
            name='detailRisques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='alimentrecette',
            unique_together={('aliment', 'recette')},
        ),
    ]
