# Generated by Django 4.0.4 on 2022-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contributeur_professionnelsante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='mineraux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='vitamines',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='originerepas',
            unique_together={('pays', 'region')},
        ),
    ]
