# Generated by Django 4.0.4 on 2022-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aliment_mineraux_alter_aliment_vitamines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='uniteComptage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
