# Generated by Django 4.0.4 on 2022-06-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aliment_unitecomptage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.IntegerField(),
        ),
    ]
