# Generated by Django 4.0.4 on 2022-06-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_message_expediteur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('contributeur', 'professionnel')},
        ),
    ]
