# Generated by Django 4.0.4 on 2022-06-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_repas_nombrenotes_repas_totalnotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='contributeur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='contributeur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='nombreNotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='repas',
            name='totalNotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contributeur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contributeur'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nombreNotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='totalNotes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
