# Generated by Django 4.0.4 on 2022-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aliment_contributeur_alter_repas_contributeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repas',
            name='nombreNotes',
        ),
        migrations.RemoveField(
            model_name='repas',
            name='totalNotes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='nombreNotes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='totalNotes',
        ),
        migrations.AlterField(
            model_name='evaluationrepas',
            name='repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.repas'),
        ),
        migrations.AlterField(
            model_name='evaluationrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.restaurant'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='momentJournee',
            field=models.IntegerField(blank=True, choices=[(1, 'Matin'), (2, 'Midi'), (3, 'Soir')], help_text='Moment habituel de consommation de ce repas', null=True, verbose_name='Moment de la journée'),
        ),
    ]
