# Generated by Django 4.0.4 on 2022-06-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_repasconsomme_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repasconsomme',
            unique_together={('date', 'momentJournee', 'contributeur')},
        ),
    ]
